name: Release Tags

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to create"
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build.yaml

  release:
    needs: build

    concurrency: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create the artifacts directory
        run: rm -rf ./artifacts && mkdir ./artifacts

      - uses: actions/download-artifact@v4.1.8
        with:
          name: magic-nix-cache-ARM64-macOS
          path: cache-binary-ARM64-macOS
      - name: Persist the cache binary
        run: cp ./cache-binary-ARM64-macOS/magic-nix-cache.closure.xz ./artifacts/ARM64-macOS

      - uses: actions/download-artifact@v4.1.8
        with:
          name: magic-nix-cache-X64-Linux
          path: cache-binary-X64-Linux
      - name: Persist the cache binary
        run: cp ./cache-binary-X64-Linux/magic-nix-cache.closure.xz ./artifacts/X64-Linux

      - uses: actions/download-artifact@v4.1.8
        with:
          name: magic-nix-cache-ARM64-Linux
          path: cache-binary-ARM64-Linux
      - name: Persist the cache binary
        run: cp ./cache-binary-ARM64-Linux/magic-nix-cache.closure.xz ./artifacts/ARM64-Linux

      - name: Rename binaries for GH release
        run: |
          mv ./artifacts/{,magic-nix-cache-closure-}ARM64-macOS
          mv ./artifacts/{,magic-nix-cache-closure-}X64-Linux
          mv ./artifacts/{,magic-nix-cache-closure-}ARM64-Linux

      - name: Publish Release to GitHub (Tag)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          target_commitish: ${{ github.sha }}
          fail_on_unmatched_files: true
          draft: true
          files: |
            artifacts/**
